# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a7856913717ab14099fbbd29d3e0086db6bee37fcc50ff638f572c8a0f79052b473048fe3699a771284c2dc030293b9ca57132ee9975638d2beaa4881d1abc

test:
  secret_key_base: 0f5ebef34bb9470553d1c9b75a70bb086f50dac939fb4578cdb27bab0c83ccefd054662ee11d1a813913f565e521c325be8116e5b8867bcb1b9781f8710227e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
